### ISSUE TITLE
Consider moving Spark jobs out of DDS object to get it cleaned up

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#206]
**Problem**

The `DDS` object has a lot of methods now and contains low level Spark transformations and computations. This makes it hard to navigate and make changes to it.

**Proposed Solution**

We could try to make the `DDS` object as lean as possible, only containing very lean function definitions for the actual core functions. They should then call some helper methods in another object that do the computations. This can either be done by creating some sort of `DDSMethods` object, or moving the stuff to the servable companion objects. This implies, e.g., that a `Histogram` knows how to construct itself from an `RDD` of numbers.

**Comment by FRosner** [comment]
@RPCMoritz what do you think?

**Comment by RPCMoritz** [comment]
Sounds very good - I would probably introduce a classical layering approach, and not mix servables and logic.
Alternatively, would it be possible to split off subsets of functions completely out of the DDS object and make them explicitly importable? For example consider a subclass DDS.Histogram (not the servable!) which gets imported when you need histogram functionality (or via wildcards) which offers the additional public methods. That would render the whole stack more modular, but introduce a slight overhead when working with DDS, since calls will be (slightly) longer and you need to manage the additional imports.

**Comment by FRosner** [comment]
Another option might be to have imports for each category (scala functions, spark core, spark graphx, spark mllib, spark sql)…

**Comment by FRosner** [comment]
I will do all of this in #211
