### ISSUE TITLE
Move to AGPLv3?

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#228]
Shall we move to AGPLv3 license?

Pros:
- Core code (my stuff, not the possible extensions others make) must remain open sourced

Cons:
- Might not be easy to integrate if your company does not allow open sourcing parts of their solution

**Comment by FRosner** [comment]
@RPCMoritz any comments / thoughts?

**Comment by RPCMoritz** [comment]
Against. Makes (full) integration into Zeppelin/Spark Notebook impossible. Makes it useless in most enterprise environments --> less potential for people to realize how awesome it is, and then commit later on, or "accidentally" while developing inside their project.
Less users = Less bug reports/feature requests.

**Comment by FRosner** [comment]
Why does it make it impossible to integrate into Zeppelin? You are allowed to use AGPLv3 code in Apache 2 licensed code as long as you don't change the license and open source the original parts? If you add something, you don't have to open source it, do you?

**Comment by RPCMoritz** [comment]
You may be able to use it, but you would effectievly make the entire project AGPLv3, at least from the point of view of those, that are not willing to disclose any source code, ever (usually for logistical and liability reasons).
If DDS remains an atomic project, AGPLv3 will not affect any prjects where it is plugged in to, but if code were to be integrated into another project, you would have to relicense the code, which just makes it more of a hassle to overcome.

From my point of view there's a general expectation in the Big Data eco system that code is either GPL or ASF licensed. AGPL is toxic to enterprise use, and GPL should be strong enough for most copyleft purposes - the "derivative" notion in AGPL is too strong, since it could be claimed that even a product developed due to insights gleaned from a DDS-based visualization would force the user to ship this code with every item.
Personally I prefer my open source to be open, and not forcibly free to the extreme.

The advantages are also pretty negligible, since I expect many people who would use DDS but not share their code, would rather violate AGPLv3 than respect it, or not use your code at all. I see no advantage for the project from that.

**Comment by FRosner** [comment]
@RPCMoritz thanks for your comment. I understand your opinion and the named freedom was the reason why I decided for Apache License in the first place. I will think about it.

**Comment by novatechflow** [comment]
Agree with @RPCMoritz. Any other license as the Apache one would kill the project.

**Comment by FRosner** [comment]
Thanks @alo-alt. So we keep it at Apache 2.
